-- MySQL Script generated by MySQL Workbench
-- Mon 27 May 2019 08:10:19 PM -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema dagyane
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dagyane
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dagyane` DEFAULT CHARACTER SET utf8 ;
USE `dagyane` ;

-- -----------------------------------------------------
-- Table `dagyane`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dagyane`.`usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nome` TEXT NOT NULL,
  `login` VARCHAR(255) NOT NULL,
  `senha` TEXT NOT NULL,
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dagyane`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dagyane`.`cliente` (
  `id_cliente` INT NOT NULL AUTO_INCREMENT,
  `nome` TEXT NOT NULL,
  `cpf_cnpj` VARCHAR(45) NULL,
  `telefone` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`id_cliente`),
  UNIQUE INDEX `telefone_UNIQUE` (`telefone` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dagyane`.`grupo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dagyane`.`grupo` (
  `id_grupo` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_grupo`),
  UNIQUE INDEX `descricao_UNIQUE` (`descricao` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dagyane`.`produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dagyane`.`produto` (
  `id_produto` INT NOT NULL AUTO_INCREMENT,
  `codigo` VARCHAR(15) NOT NULL,
  `nome` TEXT NOT NULL,
  `valor` DECIMAL(9,2) NOT NULL,
  `custo` DECIMAL(9,2) NULL,
  `observacao` TEXT NULL,
  `quantidade` INT NULL,
  `id_grupo` INT NOT NULL,
  PRIMARY KEY (`id_produto`),
  UNIQUE INDEX `codigo_UNIQUE` (`codigo` ASC),
  INDEX `fk_produto_grupo_idx` (`id_grupo` ASC),
  CONSTRAINT `fk_produto_grupo`
    FOREIGN KEY (`id_grupo`)
    REFERENCES `dagyane`.`grupo` (`id_grupo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dagyane`.`venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dagyane`.`venda` (
  `id_venda` INT NOT NULL AUTO_INCREMENT,
  `data_hora` DATETIME NOT NULL,
  `forma_pagamento` INT NOT NULL,
  `valor_total` DECIMAL(9,2) NOT NULL,
  `id_cliente` INT NULL,
  `valor_entrada` DECIMAL(9,2) NOT NULL,
  PRIMARY KEY (`id_venda`),
  INDEX `fk_venda_cliente1_idx` (`id_cliente` ASC),
  CONSTRAINT `fk_venda_cliente1`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `dagyane`.`cliente` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dagyane`.`venda_produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dagyane`.`venda_produto` (
  `id_venda_produto` INT NOT NULL AUTO_INCREMENT,
  `id_venda` INT NOT NULL,
  `id_produto` INT NOT NULL,
  `valor` DECIMAL(9,2) NOT NULL,
  `quantidade` INT NULL,
  PRIMARY KEY (`id_venda_produto`),
  INDEX `fk_venda_produto_venda1_idx` (`id_venda` ASC),
  INDEX `fk_venda_produto_produto1_idx` (`id_produto` ASC),
  CONSTRAINT `fk_venda_produto_venda1`
    FOREIGN KEY (`id_venda`)
    REFERENCES `dagyane`.`venda` (`id_venda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_venda_produto_produto1`
    FOREIGN KEY (`id_produto`)
    REFERENCES `dagyane`.`produto` (`id_produto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dagyane`.`crediario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dagyane`.`crediario` (
  `id_crediario` INT NOT NULL AUTO_INCREMENT,
  `id_venda` INT NOT NULL,
  `data_vencimento` DATETIME NOT NULL,
  `data_pagamento` DATETIME NULL,
  PRIMARY KEY (`id_crediario`),
  INDEX `fk_crediario_venda1_idx` (`id_venda` ASC),
  CONSTRAINT `fk_crediario_venda1`
    FOREIGN KEY (`id_venda`)
    REFERENCES `dagyane`.`venda` (`id_venda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
