-- MySQL Script generated by MySQL Workbench
-- Mon 20 May 2019 08:34:20 PM -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema dagyane
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dagyane
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dagyane` DEFAULT CHARACTER SET utf8 ;
USE `dagyane` ;

-- -----------------------------------------------------
-- Table `dagyane`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dagyane`.`usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nome` TEXT NOT NULL,
  `login` VARCHAR(255) NOT NULL,
  `senha` TEXT NOT NULL,
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dagyane`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dagyane`.`cliente` (
  `id_cliente` INT NOT NULL AUTO_INCREMENT,
  `nome` TEXT NOT NULL,
  `cpf_cnpj` VARCHAR(45) NULL,
  `telefone` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`id_cliente`),
  UNIQUE INDEX `telefone_UNIQUE` (`telefone` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
